### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by hainho** [hainho/philosophers#1]
- [x] input data parsing
- [x] philosophers struct 구현
- [x] infomation struct 구현
- [x] philo struct method 구현
- [x] utils function 구현
- [x] validation function 구현
- [x] free function 구현

philo struct
variable : pthread, idx, left mutex, right mutex, eat time, state
method : eat, think, sleep, check state

info struct
variable : array of philo, array of mutex, start time, input data

utils function : get cur time, atoi

validation function : check input data
